"""add country_id to profile

Revision ID: 495cb58eb9a9
Revises: c53eb56870a5
Create Date: 2026-02-21 22:15:27.238512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495cb58eb9a9'
down_revision: Union[str, Sequence[str], None] = 'c53eb56870a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'country_id')
    # ### end Alembic commands ###
