"""empty message

Revision ID: c53eb56870a5
Revises: ae10df7724ab
Create Date: 2026-02-16 21:51:28.856417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53eb56870a5'
down_revision: Union[str, Sequence[str], None] = 'ae10df7724ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('booking', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'booking', 'profile', ['user_id'], ['id'])
    op.drop_constraint(op.f('profile_country_id_fkey'), 'profile', type_='foreignkey')
    op.drop_column('profile', 'country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('profile_country_id_fkey'), 'profile', 'country', ['country_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.alter_column('booking', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('booking', 'user_id')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
